name: First Workflow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps: 
            - name: Run first command
              run: echo "Hello, World!"

            - name: Command in multiple lines
              run: |
                python --version: '3.11'
                pip --version: '23.0.1'

                

