name: Second Workflow
on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Display Python and Pip versions on Ubuntu
              run: |
                python --version
                pip --version
    run-parallel-command:
        runs-on: debian-latest
        steps:
            - name: Display Python and Pip versions on Debian
              run: |
                python --version 
                pip --version 
    run-second-command:
        runs-on: ubuntu 22.04
        needs: run-first-command
        steps:
            - name: Display Python and Pip versions on Ubuntu 22.04
              run: 
                python --version
                pip --version