name: Second Workflow
on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Display Python and Pip versions on Ubuntu
              run: |
                python --version
                pip --version
    run-parallel-command:
        runs-on: debian-latest
        steps:
            - name: Display Python and Pip versions on Debian
              run: |
                python --version 
                pip --version 
    run second-command:
        runs-on: windows-latest
        needs: run_first-command
        steps:
            - name: Display Python and Pip versions on Windows
              run: 
                python --version
                pip --version