name: Third Workflow
on: push

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps: 
            - name: List Files and Copy Repository
              run: ls -a
            - uses: actions/checkout@v4
            - name: List Files and Copy Repository
              run: ls -a